version: 2
updates:
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
    groups:
      spring:
        patterns: ['org.springframework*', 'io.spring*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: monthly
