#!/usr/bin/env python3
"""Export the API's responses into a static snapshot the prototype can use when no API is running.

Usage: python3 scripts/export_snapshot.py [API_BASE] [OUTPUT_JS]
Defaults: http://localhost:8080 → ../../design/prototype/data/sca-snapshot.js

The snapshot contains exactly what the API returned for the paths the prototype pages request, so the pages
render identical data either way. It is labelled with its export time and shown as a snapshot in the UI.
"""
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone

SORTS = {
    "batting": ["runs", "average", "strikerate", "sixes", "name"],
    "bowling": ["wickets", "economy", "average", "strikerate", "name"],
    "fielding": ["catches", "dismissals", "stumpings", "runouts", "name"],
}

PATHS = [
    "/api/sca/record",
    "/api/sca/leaders?top=1",
    "/api/sca/leaders?top=3",
    "/api/sca/players",
    "/api/sca/results",
    "/api/sca/results?limit=1",
    "/api/sca/results?limit=3",
    "/api/sca/results?limit=5",
    "/api/sca/schedule?limit=5",
    "/api/sca/schedule?includePast=true",
    "/api/sca/schedule/next",
    "/api/sca/sync/status",
] + [f"/api/sca/{kind}?sort={s}" for kind, sorts in SORTS.items() for s in sorts]


def fetch(base, path):
    with urllib.request.urlopen(base + path, timeout=15) as res:
        if res.status == 204:
            return {"data": None, "meta": {"sources": []}}
        return json.load(res)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    base = (sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8080").rstrip("/")
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "..", "..", "..", "design", "prototype", "data", "sca-snapshot.js")
    responses = {}
    for path in PATHS:
        try:
            responses[path] = fetch(base, path)
        except urllib.error.URLError as e:
            sys.exit(f"Failed to fetch {path}: {e}")
    snapshot = {
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "Hawks API responses built from the SCA CSV exports (scores.cricketsingapore.com)",
        "responses": responses,
    }
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("/* Generated by apps/api/scripts/export_snapshot.py — do not edit by hand. */\n")
        f.write("window.HAWKS_SCA_SNAPSHOT = ")
        json.dump(snapshot, f, indent=1, ensure_ascii=False)
        f.write(";\n")
    print(f"Wrote {len(responses)} responses to {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
